-- MySQL Script generated by MySQL Workbench
-- 11/12/15 19:51:04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`STATISTIC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`STATISTIC` (
  `statisticId` INT NOT NULL AUTO_INCREMENT,
  `statisticGameNumber` INT NOT NULL,
  `statisticVoteNumber` INT NOT NULL,
  `statisticVoteAverage` FLOAT NULL,
  `statisticWonGame` INT NOT NULL,
  `statisticLostGame` INT NOT NULL,
  PRIMARY KEY (`statisticId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`USER` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `userPseudo` VARCHAR(20) NOT NULL,
  `userPassword` VARCHAR(80) NOT NULL,
  `userQuestion` VARCHAR(100) NOT NULL,
  `userAnswer` VARCHAR(100) NOT NULL,
  `userStatisticId` INT NULL,
  PRIMARY KEY (`userId`),
  INDEX `fk_statistic_id_idx` (`userStatisticId` ASC),
  CONSTRAINT `fk_statistic_id`
    FOREIGN KEY (`userStatisticId`)
    REFERENCES `mydb`.`STATISTIC` (`statisticId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ITEMTYPE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ITEMTYPE` (
  `itemTypeId` INT NOT NULL AUTO_INCREMENT,
  `itemTypeName` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`itemTypeId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ITEMLOCATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ITEMLOCATION` (
  `itemLocationId` INT NOT NULL AUTO_INCREMENT,
  `itemLocationName` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`itemLocationId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ITEMSCARCITY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ITEMSCARCITY` (
  `itemScarcityId` INT NOT NULL AUTO_INCREMENT,
  `itemScarcityName` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`itemScarcityId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ITEM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ITEM` (
  `itemId` INT NOT NULL AUTO_INCREMENT,
  `itemCondition` VARCHAR(100) NOT NULL,
  `itemType` INT NOT NULL,
  `itemLocation` INT NOT NULL,
  `itemName` VARCHAR(20) NOT NULL,
  `itemCaracteristic` VARCHAR(100) NOT NULL,
  `itemScarcity` INT NOT NULL,
  `itemSellingPrice` INT NOT NULL,
  `itemDescription` TEXT NULL,
  `itemSpriteId` INT NOT NULL,
  PRIMARY KEY (`itemId`),
  INDEX `fk_itemType_id_idx` (`itemType` ASC),
  INDEX `fk_itemLocation_id_idx` (`itemLocation` ASC),
  INDEX `fk_itemScarcity_id_idx` (`itemScarcity` ASC),
  CONSTRAINT `fk_itemType_id`
    FOREIGN KEY (`itemType`)
    REFERENCES `mydb`.`ITEMTYPE` (`itemTypeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_itemLocation_id`
    FOREIGN KEY (`itemLocation`)
    REFERENCES `mydb`.`ITEMLOCATION` (`itemLocationId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_itemScarcity_id`
    FOREIGN KEY (`itemScarcity`)
    REFERENCES `mydb`.`ITEMSCARCITY` (`itemScarcityId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CLASSROLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CLASSROLE` (
  `classRoleId` INT NOT NULL AUTO_INCREMENT,
  `classRoleName` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`classRoleId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CLASS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CLASS` (
  `classId` INT NOT NULL AUTO_INCREMENT,
  `classRole` INT NOT NULL,
  `classAttribut` VARCHAR(100) NOT NULL,
  `classSkill` VARCHAR(100) NOT NULL,
  `classDescription` TEXT NULL,
  `classSpriteID` INT NOT NULL,
  PRIMARY KEY (`classId`),
  INDEX `fk_classRole_id_idx` (`classRole` ASC),
  CONSTRAINT `fk_classRole_id`
    FOREIGN KEY (`classRole`)
    REFERENCES `mydb`.`CLASSROLE` (`classRoleId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SKILLTARGET`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SKILLTARGET` (
  `skillTargetID` INT NOT NULL AUTO_INCREMENT,
  `skillTargetName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`skillTargetID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SKILL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SKILL` (
  `skillID` INT NOT NULL AUTO_INCREMENT,
  `skillName` VARCHAR(45) NOT NULL,
  `skillDescription` TEXT NULL,
  `skillTarget` INT NOT NULL,
  `skillEffectCode` VARCHAR(100) NOT NULL,
  `skillSpriteId` INT NULL,
  PRIMARY KEY (`skillID`),
  INDEX `fk_skillTarger_id_idx` (`skillTarget` ASC),
  CONSTRAINT `fk_skillTarger_id`
    FOREIGN KEY (`skillTarget`)
    REFERENCES `mydb`.`SKILLTARGET` (`skillTargetID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MONSTER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MONSTER` (
  `monsterID` INT NOT NULL AUTO_INCREMENT,
  `monsterName` VARCHAR(45) NOT NULL,
  `monsterDescription` TEXT NULL,
  `monsterAttribut` VARCHAR(100) NOT NULL,
  `monsterSkill` VARCHAR(100) NOT NULL,
  `monsterSpriteID` INT NOT NULL,
  PRIMARY KEY (`monsterID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`NPC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`NPC` (
  `npcID` INT NOT NULL AUTO_INCREMENT,
  `npcName` VARCHAR(45) NOT NULL,
  `npcDescription` TEXT NULL,
  `npcAction` VARCHAR(20) NOT NULL,
  `npcSpriteID` INT NOT NULL,
  PRIMARY KEY (`npcID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DECOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DECOR` (
  `decorID` INT NOT NULL,
  `decorName` VARCHAR(45) NOT NULL,
  `decorSpriteId` INT NOT NULL,
  PRIMARY KEY (`decorID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DICE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DICE` (
  `diceId` INT NOT NULL AUTO_INCREMENT,
  `diceName` VARCHAR(45) NOT NULL,
  `diceSpriteId` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`diceId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OBJECT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OBJECT` (
  `objectId` INT NOT NULL AUTO_INCREMENT,
  `objectName` VARCHAR(45) NOT NULL,
  `objectSpriteId` INT NOT NULL,
  PRIMARY KEY (`objectId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TABLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TABLE` (
  `tableId` INT NOT NULL AUTO_INCREMENT,
  `tableName` VARCHAR(45) NOT NULL,
  `tableSpriteId` INT NOT NULL,
  PRIMARY KEY (`tableId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BUBBLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BUBBLE` (
  `bubbleId` INT NOT NULL AUTO_INCREMENT,
  `bubbleName` VARCHAR(45) NOT NULL,
  `bubbleSpriteId` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`bubbleId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`INTERFACE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`INTERFACE` (
  `interfaceId` INT NOT NULL AUTO_INCREMENT,
  `interfaceName` VARCHAR(45) NOT NULL,
  `interfaceSpriteId` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`interfaceId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`NPCACTION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`NPCACTION` (
  `npcActionId` INT NOT NULL AUTO_INCREMENT,
  `npcActionName` VARCHAR(45) NOT NULL,
  `npcActionData` TEXT NULL,
  PRIMARY KEY (`npcActionId`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
